### PR TITLE
Upgrade typescript, typedoc, add @types/node and adjust code accordingly

### PR DESCRIPTION
**Pull request by marcjansen**
This PR suggests to

* upgrade `typescript` from `^4.8.4` to `^5.1.6`
* ~~upgrade `typedoc` from `^0.24.1` to `^0.24.8`~~ This was no longer needed, after rebase
* add `@types/node` in version `^20.5.6`

The deprecated typescript config `suppressImplicitAnyIndexErrors` is removed from the config, and some files had updates wrt the typing of Objects where the keys are of type `string`, see a86723f4fd0970305a0c775690363fefd9641f18.

Once that was done, a new typescript error showed up: TS 7030 "Not all code paths return a value". 328d7e36a87e4457ed4b32dcc97d4a7b38853c6c fixes the error. The `return` looks dubious to me, and the method is overly complex already. One cannot stop/break `forEach` with `return`, so I am unsure what the lines were actually doing. Tests still pass, but **this *might* be breaking change**, so extra careful review is recommended here.

On a side note, `ObjectUtil.getValue` should be refactored, the TODOs addressed or it should be deprecated/removed altogether.

### CODE REVIEW

**Review by ahennr — APPROVED** [review]
LGTM, plz merge.

**Comment by marcjansen** [comment]
Thanks for the review, @ahennr !

I rebased this PR, can you please have another look and do you think https://github.com/terrestris/base-util/pull/1008/commits/3836d254c9d128e87821d9a03967413bba88032d is OK?

**Comment by ahennr** [comment]
> Thanks for the review, @ahennr !
> 
> I rebased this PR, can you please have another look and do you think [3836d25](https://github.com/terrestris/base-util/commit/3836d254c9d128e87821d9a03967413bba88032d) is OK?

👍🏼

**Review by ahennr — APPROVED** [review]

**Comment by marcjansen** [comment]
Thanks again, @ahennr :-*

**Pull request merged**
