### PR TITLE
Add array util

### PR DESCRIPTION
**Pull request by hwbllmnn**
See the comments.

@terrestris/devs Please review.

### CODE REVIEW

**Review by marcjansen — APPROVED** [review]
Code looks fine, I would have expected one added indentation level of `describe` in the test for the `joinArrayWith` function, but this is just minor. 

I wonder where we need this, tbh. If you think this qualifies as a shared and reusable method in this utility library, than go for it :-)

**Comment by hwbllmnn** [comment]
> Code looks fine, I would have expected one added indentation level of `describe` in the test for the `joinArrayWith` function, but this is just minor.

The missing indentation level results from this util function being just a function contrary to the other utils which are defined as classes with static methods.

> I wonder where we need this, tbh. If you think this qualifies as a shared and reusable method in this utility library, than go for it :-)

Imagine you have an array with values which you map to JSX list entries. Then you want to insert dividers between them :-)

**Comment by dnlkoch** [comment]
Why did you break with the current structure of static methods in classes?

**Comment by dnlkoch** [comment]
Absolutely right, but now we have two different API approaches in this util what might confuse users.

**Pull request merged**
